Neos:
  Flow:
    persistence:
      backendOptions:
        dbname: 'flow_functional_testing'
    i18n:
      defaultLocale: de
  ContentRepository:
    contentDimensions:
      language:
        label: Languages
        icon: language
        # The default dimension that is applied when creating nodes without specifying a dimension
        default: de
        # The default preset to use if no URI segment was given when resolving languages in the router
        defaultPreset: de
        presets:
          de:
            label: Deutsch
            values:
              - de
            uriSegment: ''
          en:
            label: English
            values:
              - en
              - de
            uriSegment: 'en'
            options:
              translationStrategy: 'sync'
          it:
            label: Italiano
            values:
              - it
              - de
            uriSegment: 'it'
            options:
              translationStrategy: 'once'
#Sitegeist:
#  LostInTranslation:
#    nodeTranslation:
#      skipAuthorizationChecks: true
#    DeepLApi:
#      enableCache: true
#      authenticationKey: '%env:DEEPL_AUTHENTICATION_KEY%'
#      defaultOptions:
#        splitting_tags: 'br'
#      ignoredTerms:
#        - 'Code Q'
#        - 'Innsbruck Marketing GmbH'
#        - 'Innsbruck Marketing'
#        - 'Nordkette'
#        - 'Mag.'
#        - 'Dr.'
#        - 'Dipl.Ing.'
#        - 'Dipl.-Ing.'
