Neos:
  Fusion:
    defaultContext:
      'Sitegeist.LostInTranslation': 'Sitegeist\LostInTranslation\Eel\TranslationHelper'
  Neos:
    fusion:
      autoInclude:
        'Sitegeist.LostInTranslation': true
    modules:
      management:
        submodules:
          sitegeist_lostintranslation:
            label: 'Lost In Translations'
            description: 'DeepL based Translations for Neos'
            icon: 'icon-language'
            controller: 'Sitegeist\LostInTranslation\Controller\LostInTranslationModuleController'
            privilegeTarget: 'Sitegeist.LostInTranslation:AccessBackendModule'
  Flow:
    mvc:
      routes:
        'Sitegeist.LostInTranslation':
          position: 'start 1'
    security:
      authentication:
        providers:
          Neos.Neos:Backend:
            requestPatterns:
              'Sitegeist.LostInTranslation:Controllers.CollectionTranslation':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Sitegeist\LostInTranslation\Controller\CollectionTranslationController'
