Sitegeist:
  LostInTranslation:
    DeepLApi:

      #
      # This package needs an authenticationKey for the DeeplL Api from https://www.deepl.com/pro-api.
      # There are free plans that support a limited number but for productive use we recommend using a payed plan.
      #
      authenticationKey: ''

      baseUri: 'https://api.deepl.com/v2/'
      baseUriFree: 'https://api-free.deepl.com/v2/'

      defaultOptions:
        tag_handling: 'xml'
        split_sentences: 'nonewlines'
        preserve_formatting: 1
        formality: "default"

    nodeTranslation:
      #
      # Enable the automatic translations of nodes while they are adopted to another dimension
      #
      enabled: true

      #
      # There are two strategies:
      # (*) once: will translate the node once the editor switches the language dimension and only then
      # (*) sync: will translate and sync the node anytime the base language has been edited
      #
      strategy: 'once'

      #
      # Translate all inline editable fields without further configuration.
      #
      # If this is disabled iline editables can be configured for translation by setting
      # `options.translateOnAdoption: true` for each property seperatly
      #
      translateInlineEditables: true

      #
      # The name of the language dimension. Usually needs no modification
      #
      languageDimensionName: 'language'

      #
      # When strategy "sync" is selected, this setting defines which languages
      # to translate to which other languages
      #
      # This example would sync and translate all nodes in language "de" to "it" and "en"
      #
      # translationMapping:
      #   de:
      #     - 'it'
      #     - 'en'
      #
      translationMapping: [ ]
